name: Deploy Website to S3 

on:
  push:
    branches:
      - main  # This triggers the action when a push to the 'main' branch occurs

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Node.js environment (for building React app)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the Node.js version you need for your project

      # Step 3: Navigate to the website folder and install dependencies
      - name: Install dependencies
        run: |
          cd swin_rover_app  # Navigate to the folder containing the React project
          npm install

      # Step 4: Build the React app (assuming it's a React project)
      - name: Build React app
        run: |
          cd swin_rover_app  # Ensure we're in the website folder
          npm run build  # Run the build script to generate static files in the 'build' directory

      # Step 5: Deploy the built website to S3
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete  # Make the files publicly readable and delete old files
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2
          AWS_S3_BUCKET: swinroverteam.com  # Replace with your actual bucket name
          SOURCE_DIR: swin_rover_app/dist  # The dist directory where the static files are generated
